### Frontend
GET http://172.16.18.44:3000


### test
GET http://localhost:3001/test

###
GET http://localhost:3001/api/user

### Get all users
GET http://localhost:3001/api/users
### make user
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
    "name":"Prajwal",
    "email":"pp@foo.bar",
    "password":"password"
}
### login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email":"pp@foo.bar",
    "password":"password"
}
### getting all models 
GET http://localhost:3001/api/models
### getting all models - csv
GET http://localhost:3001/api/models/csv
### getting all preds - json
GET http://172.16.18.42:3001/api/models/preds/1
### getting all models - csv 
GET http://localhost:3001/api/models/preds/1/csv
### getting all models - csv 
GET http://localhost:3001/api/models/preds/1/csv

### ADD
POST http://localhost:3001/api/models
Content-Type: application/json

{
    "model_desc":"Nandi Toyota UTrust All Branch- Trade-in",
    "model_loc":"UTrust_TradeIn_DT_1.1.rds",
    "data_loc":"Nandi Toyota Utrust All Branch-Trade-in.csv"
}

### get list of models
GET http://localhost:3001/api/files/models

### get list of data
GET http://localhost:3001/api/files/data

### upload
POST http://localhost:3001/api/files/
