# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  db:
    image: mysql
    hostname: db
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_DATABASE=seven2seven
      - MYSQL_USER=seven2seven
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mysqldata: null
  mongodbdata: null
  redisdata: null
